services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        NEXT_PUBLIC_ENV: ${NEXT_PUBLIC_ENV}
        NEXT_PUBLIC_BACK_URL_DEV: ${NEXT_PUBLIC_BACK_URL_DEV}
        NEXT_PUBLIC_BACK_URL: ${NEXT_PUBLIC_BACK_URL}
        NEXT_PUBLIC_FRONT_URL_DEV: ${NEXT_PUBLIC_FRONT_URL_DEV}
        NEXT_PUBLIC_FRONT_URL: ${NEXT_PUBLIC_FRONT_URL}
    env_file:
      - ./env
    ports:
      - "3001:3001"
