FROM node:20 AS builder

WORKDIR /app

RUN corepack enable && corepack prepare yarn@4.9.2 --activate

COPY package.json yarn.lock .yarnrc.yml turbo.json ./
COPY packages/ ./packages/
COPY apps/server ./apps/server

RUN yarn install

RUN yarn turbo build --filter=server...

ENV NODE_PATH=/app/node_modules

EXPOSE 3000

CMD ["yarn", "workspace", "server", "start"]
